name: example
resolution: workspace
description: Demonstrates how to use the macos_ui package
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  macos_ui:
    path: ..
  provider: ^6.1.5
  google_fonts: ^4.0.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/sf_symbols/
